name: Build and Deploy Pelican Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install pelican markdown ghp-import

    - name: Build Pelican site
      run: pelican content -s publishconf.py

    - name: Deploy to GitHub Pages using PAT
      env:
        TOKEN: ${{ secrets.HAIMING }}
      run: |
        git config --global user.name "haiminggroup"
        git config --global user.email "haiminggroup@gmail.com"
        ghp-import output -b gh-pages
        git push https://$TOKEN@github.com/${{ github.repository }} gh-pages --force


    
