name: Build and Deploy Pelican Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican markdown ghp-import

    - name: Build site with Pelican
      run: pelican content -s publishconf.py

    - name: Deploy to GitHub Pages
      run: |
        ghp-import output -b gh-pages -p
